# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: 
  - jekyll-paginate-v2
  - jemoji
  - font-awesome-sass

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Matías Mattamala's website
description: "Personal website"
keywords: "Matías Mattamala, Matías, Mattamala, robotics, perception, legged robots, computer vision, state estimation, SLAM"
url: http://mmattamala.github.io
baseurl: ""

google_analytics: UA-126017634-1
repo: http://github.com/mmattamala/mmattamala.github.io
disqus_shortname: "nandothemes"
disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: Matías Mattamala
  job: roboticist
  interests: the interaction of perception and control in robotics
  bio: "I'm a final-year PhD (DPhil) student in the [**Dynamic Robot Systems Group (DRS)**](https://ori.ox.ac.uk/labs/drs/) of the [**Oxford Robotics Institute**](https://ori.ox.ac.uk/), supervised by [**Maurice Fallon**](https://ori.ox.ac.uk/people/maurice-fallon/)." 
  news: "**News:** After 6 months at ETH Zurich, I'm back in Oxford for the last project of my PhD. I expect to graduate before September 2023."
       

  thumb: /images/mm2019.jpg
  email: matias@robots.ox.ac.uk
  url: https://mmattamala.github.io/
  github: https://github.com/mmattamala
  linkedin: https://linkedin.com/in/mmattamala
  google_scholar: https://scholar.google.co.uk/citations?hl=en&user=R5aRkHUAAAAJ&view_op=list_works&authuser=1&sortby=pubdate
  instagram: https://instagram.com/mmattamala
  researchgate: https://www.researchgate.net/profile/Matias_Mattamala
  arxiv: https://instagram.com/mmattamala
  twitter: https://twitter.com/mmattamala
  mastodon: https://mastodon.social/@mmattamala/
  cv_link: data/mm_cv_en.pdf

# navbar pages
navbar:
  - slug: about
    title: about
  - slug: publications
    title: publications
  - slug: blog
    title: blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
