# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Matías Mattamala's website
description: "Personal website"
keywords: "Matías Mattamala, Matías, Mattamala, robotics, perception, legged robots"
url: http://mmattamala.github.io
baseurl: ""

google_analytics: UA-126017634-1
repo: http://github.com/mmattamala/mmattamala.github.io
disqus_shortname: "nandothemes"
disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: Matías Mattamala
  job: roboticist
  interests: legged robots and perception
  bio: I'm a PhD (DPhil) student in the [**Dynamic Robot Systems Group (DRS)**](https://ori.ox.ac.uk/labs/drs/) of the [**Oxford Robotics Institute**](https://ori.ox.ac.uk/), under the supervision of [**Assoc. Prof. Maurice Fallon**](https://ori.ox.ac.uk/people/maurice-fallon/). 
      <br>
      I'm working on long-term visual navigation for legged robots.
      <br><br>
      I hold a M.Sc in Electrical Engineering from the [**Universidad de Chile**](https://www.uchile.cl). My thesis was related to Visual SLAM for NAO robots. [**Video**](https://www.youtube.com/watch?v=ED_H3ngLncA) and [**full document**](http://repositorio.uchile.cl/bitstream/handle/2250/168075/Localizaci%c3%b3n-visual-en-robots-de-recursos-computacionales-limitados.pdf?sequence=1&isAllowed=y).
       

  thumb: /images/mm2019.jpg
  email: matias@robots.ox.ac.uk
  url: https://mmattamala.github.io/
  github: https://github.com/mmattamala
  linkedin: https://linkedin.com/in/mmattamala
  google_scholar: https://scholar.google.cl/citations?user=R5aRkHUAAAAJ&hl=es
  instagram: https://instagram.com/mmattamala
  researchgate: https://www.researchgate.net/profile/Matias_Mattamala
  arxiv: https://instagram.com/mmattamala
  twitter: https://twitter.com/mmattamala
  cv_link: data/mm_cv_en.pdf

# navbar pages
navbar:
  # slug: about
  #  title: About
  #- slug: icons
  #  title: Icons
  #- slug: blog
  #  title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
