# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
kramdown:
  math_engine: mathjax
  parse_block_html: true

highlighter: pygments
plugins: 
  - jekyll-paginate-v2
  - jemoji
  - font-awesome-sass
  - jekyll-diagrams
  - jekyll-mermaid

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"
  sort_field: 'date'
  sort_reverse: true
comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Matías Mattamala's website
description: "Personal website"
keywords: "Matías Mattamala, Matías, Mattamala, robotics, perception, legged robots, computer vision, state estimation, SLAM, navigation, field robotics, remote sensing"
url: http://mmattamala.github.io
baseurl: ""

# google_analytics: UA-126017634-1
# google_analytics: G-STLML2SPMS # mattmatta
google_analytics: G-K0YVZTFTRV
repo: http://github.com/mmattamala/mmattamala.github.io
disqus_shortname: "matiasmattamala"
disqus_site_shortname: "mmattamala"

# Author settings
author:
  name: Matías Mattamala
  job: roboticist
  interests: foundations and systems for autonomy
  bio: "I'm currently a Research Associate in the **Centre for AI in Assistive Autonomy**, School of Informatics, University of Edinburgh. I'm researching robotic systems for assistive applications." 
  news: "**News:** I've been invited as a speaker to the [International Workshop of Intelligent Autonomous Learning Systems 2025](https://www.ias.informatik.tu-darmstadt.de/Workshops/IWIALS). I gave a spotlight talk on my recent research on robot autonomy (e.g., our new [T-FR](https://ieeexplore.ieee.org/document/11053872)), as well as a tutorial on [designing graphics for papers](https://docs.google.com/presentation/d/161ckSI_LVptLwFSiT3hCMhK-5gGf_vDdwmTOq54YRF8/edit?usp=drive_web&ouid=112051573251406531065)."
       

  thumb: /images/mm2024.jpg
  email: matias@robots.ox.ac.uk
  url: https://mmattamala.github.io/
  github: https://github.com/mmattamala
  linkedin: https://linkedin.com/in/mmattamala
  google_scholar: https://scholar.google.co.uk/citations?hl=en&user=WYijA64AAAAJ&view_op=list_works&sortby=pubdate
  instagram: https://instagram.com/mmattamala
  researchgate: https://www.researchgate.net/profile/Matias_Mattamala
  arxiv: https://instagram.com/mmattamala
  twitter: https://twitter.com/mmattamala
  bluesky: https://bsky.app/profile/mmattamala.bsky.social
  mastodon: https://mastodon.social/@mmattamala/
  cv_link: /data/mm_cv.pdf

# navbar pages
navbar:
  - slug: about
    title: about
  - slug: publications
    title: publications
  - slug: blog
    title: blog
  - slug: fun
    title: fun

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
