# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
kramdown:
  math_engine: mathjax
  parse_block_html: true

highlighter: pygments
plugins: 
  - jekyll-paginate-v2
  - jemoji
  - font-awesome-sass
  - jekyll-diagrams
  - jekyll-mermaid

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"
  sort_field: 'date'
  sort_reverse: true
comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Matías Mattamala's website
description: "Personal website"
keywords: "Matías Mattamala, Matías, Mattamala, robotics, perception, legged robots, computer vision, state estimation, SLAM, navigation"
url: http://mmattamala.github.io
baseurl: ""

# google_analytics: UA-126017634-1
# google_analytics: G-STLML2SPMS # mattmatta
google_analytics: G-K0YVZTFTRV
repo: http://github.com/mmattamala/mmattamala.github.io
disqus_shortname: "matiasmattamala"
disqus_site_shortname: "mmattamala"

# Author settings
author:
  name: Matías Mattamala
  job: roboticist
  interests: robot perception and navigation
  bio: "I'm also a Postdoctoral Researcher in the [**Dynamic Robot Systems Group (DRS)**](https://ori.ox.ac.uk/labs/drs/), enabling robots to achieve autonomous surveying and monitoring missions in the wild." 
  news: "**News:** I defended my PhD thesis last November 17th 2023!"
       

  thumb: /images/mm2019.jpg
  email: matias@robots.ox.ac.uk
  url: https://mmattamala.github.io/
  github: https://github.com/mmattamala
  linkedin: https://linkedin.com/in/mmattamala
  google_scholar: https://scholar.google.co.uk/citations?hl=en&user=R5aRkHUAAAAJ&view_op=list_works&authuser=1&sortby=pubdate
  instagram: https://instagram.com/mmattamala
  researchgate: https://www.researchgate.net/profile/Matias_Mattamala
  arxiv: https://instagram.com/mmattamala
  twitter: https://twitter.com/mmattamala
  mastodon: https://mastodon.social/@mmattamala/
  cv_link: data/mm_cv_en.pdf

# navbar pages
navbar:
  - slug: about
    title: about
  - slug: publications
    title: publications
  - slug: blog
    title: blog
  - slug: fun
    title: fun

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
